language: generic # setting language to C will override cross-compiler and fail

sudo: required
dist: trusty

env:
  global:
    - ZEPHYR_GCC_VARIANT=zephyr
    - ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
    - ZEPHYR_BASE=$TRAVIS_BUILD_DIR/deps/zephyr
    - ZEPHYR_SDK_VERSION=0.8.2
    - ZEPHYR_SDK_DOWNLOAD_FOLDER=https://nexus.zephyrproject.org/content/repositories/releases/org/zephyrproject/zephyr-sdk/$ZEPHYR_SDK_VERSION-i686
    - ZEPHYR_SDK_SETUP_BINARY=zephyr-sdk-$ZEPHYR_SDK_VERSION-i686-setup.run
    - ZEPHYR_SDK_DOWNLOAD_URL=$ZEPHYR_SDK_DOWNLOAD_FOLDER/$ZEPHYR_SDK_SETUP_BINARY
  matrix:
    - TARGET="git-check" NOZEPHYR=y
    - TARGET="zephyr"
    - TARGET="zephyr-large" PARTSIZE=256
    - TARGET="BOARD=frdm_k64f"
    - TARGET="arc"
    - TARGET="linux" NOZEPHYR=y

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install make gcc g++ python3-ply ncurses-dev uglifyjs sysvbanner -qq

install: >
  if [ "$NOZEPHYR" != "y" ]; then
    wget $ZEPHYR_SDK_DOWNLOAD_URL &&
    chmod +x $ZEPHYR_SDK_SETUP_BINARY &&
    ./$ZEPHYR_SDK_SETUP_BINARY --quiet -- -y -d $ZEPHYR_SDK_INSTALL_DIR > /dev/null;
  fi

before_script: >
  if [ "$NOZEPHYR" != "y" ]; then
    source zjs-env.sh $PARTSIZE &&
    make update &&
    source deps/zephyr/zephyr-env.sh
  else
    source zjs-env.sh
  fi

script: >
  if [ "$TARGET" == "zephyr" ]; then
    banner "Test 1/7" &&
    make V=1 &&
    banner "Test 2/7" &&
    make V=1 JS=samples/TrafficLight.js &&
    banner "Test 3/7" &&
    make V=1 JS=samples/PWM.js &&
    banner "Test 4/7" &&
    make V=1 JS=samples/I2C.js &&
    banner "Test 5/7" &&
    make V=1 JS=samples/UART.js &&
    banner "Test 6/7" &&
    make V=1 JS=samples/tests/Events.js &&
    banner "Test 7/7" &&
    make V=1 JS=tests/test-performance.js
  elif [ "$TARGET" == "zephyr-large" ]; then
    banner "Test 1/1" &&
    make V=1 JS=samples/WebBluetoothGroveLcdDemo.js
  elif [ "$TARGET" == "git-check" ]; then
    # check for any new trailing whitespace since the first fetched commit
    banner "git check" &&
    git diff --check HEAD~49
  else
    banner "Test 1/1" &&
    make V=1 $TARGET;
  fi
